#!/bin/bash
#PBS -l nodes=8:ppn=14
#PBS -l walltime=48:00:00
#PBS -N mesa_cauchy_grid
#PBS -q long
#PBS -j oe
#PBS -o mesa_cauchy_grid.txt

module load shared
module load maui
module load torque
module load mvapich2/gcc/64/2.2rc1
module load gcc
module load anaconda/3

source /gpfs/home/dwillcox/codes/mesa-for-UQ/setup_mesa.sh

export PATH="/gpfs/home/dwillcox/job-run-scripts:$PATH"

export OMP_NUM_THREADS=1

cd $PBS_O_WORKDIR

mpirun -n 112 mpiproc_exec run_mesa.tasks


