#!/usr/bin/env python
"""
Chains together and submits a repeated job using qsub.

Takes three arguments:
1) Name of run script (with the aprun command)
2) Initial Job ID to wait on (Optional)
3) Number of times to submit the run script (Optional, Default is 1)

Usage: Chain together 8 qsub's of titan.run
$ chainsub titan.run -n 8
"""
from __future__ import print_function
import argparse
from subprocess import Popen, PIPE

parser = argparse.ArgumentParser()
parser.add_argument('runscript', type=str,
                    help='Name of run script to submit repeatedly.')
parser.add_argument('-w', '--initialwait', type=str, 
                    help='Job ID to wait on at start of chain, if any.')
parser.add_argument('-n', '--nsubmissions', type=int, default=1,
                    help='Number of times to submit the run script. (Default 1)')
args = parser.parse_args()

ndepends = -1
for i in range(args.nsubmissions):
    if i == 0 and args.initialwait:
        ndepends = args.initialwait
    cmdlist = ['qsub']
    if ndepends != -1:
        cmdlist += ['-W', 'depend=afterany:{}'.format(ndepends)]
    cmdlist += [args.runscript]
    cmdstr = ' '.join(cmdlist)
    proc = Popen(cmdstr, stdout=PIPE, stderr=PIPE, shell=True)
    out, err = proc.communicate()
    out = out.decode('utf-8')
    err = err.decode('utf-8')
    ndepends = out.split()[0]
    print(out)
    print(err)
